### ISSUE TITLE
在linux中，启动失败，是不是因为CPU或者内存不足呢

### ISSUE THREAD

**Issue by AlienTQH** [weibaohui/k8m#1]
报错如下：I1202 17:45:25.132287    4949 callbacks.go:10] Register RegisterDefaultCallbacks func  to clusters
I1202 17:45:25.132553    4949 main.go:39] 版本: v1.0.0
I1202 17:45:25.132561    4949 main.go:40] Git Commit: ead3299
I1202 17:45:25.132598    4949 cluster.go:194] Show Clusters
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1918079]

goroutine 1 [running]:
github.com/weibaohui/kom/kom.DefaultCluster(...)
        /root/go/lib/pkg/mod/github.com/weibaohui/kom@v0.0.28/kom/cluster.go:53
github.com/weibaohui/k8m/pkg/callback.RegisterCallback()
        /root/code/k8m/pkg/callback/cb.go:9 +0xd9
main.Init()
        /root/code/k8m/main.go:45 +0x20a
main.main()
        /root/code/k8m/main.go:56 +0x1f

**Comment by weibaohui** [comment]
看日志应该是没有链接上k8s集群。可加我vx:Ox1df5e76

**Comment by weibaohui** [comment]
程序启动默认会去读取当前用户名下的~/.kube/config文件，请查看下是否存在这个文件？看日志应该没有这个文件。

**Comment by weibaohui** [comment]
最新版已增加对该类异常的提示。
