### ISSUE TITLE
AI功能未启用

### ISSUE THREAD

**Issue by BinchenQ** [weibaohui/k8m#4]
启动k8m时，指定了 gpt api-key和url，但在使用AI相关功能时，提示：
![image](https://github.com/user-attachments/assets/a8b5a5e0-8757-4c3f-af3f-e6128e357dd9)
请先配置开启ChatGPT功能

使用的是最新版本
![image](https://github.com/user-attachments/assets/c4991461-d3e6-4bc8-8723-2a9863cf7b50)

**Comment by weibaohui** [comment]
GPT功能首先会看env环境变量中是否有如下两个环境变量
export OPENAI_API_KEY="sk-XXXXX"
export OPENAI_API_URL="https://api.siliconflow.cn/v1"
如果两个都配置了才会算是启用。请您检查env中的变量设置情况，是否已经设置了。

**Comment by weibaohui** [comment]
为方便查看状态，在[3ecd1b6](https://github.com/weibaohui/k8m/commit/3ecd1b6fe512efa38f6d20ead4530fe384d35c4a)Commit中，增加的对GPT状态的日志输出
