### ISSUE TITLE
namespace加个过滤框

### ISSUE THREAD

**Issue by zhaomingcheng01** [weibaohui/k8m#7]
![image](https://github.com/user-attachments/assets/97eaadc2-c527-4a8f-afdc-1fde96ae4d2e)

**Comment by weibaohui** [comment]
安排!

**Comment by weibaohui** [comment]
[https://github.com/weibaohui/k8m/commit/f50276dac50ce97e848eccbf2690e537e2994601](https://github.com/weibaohui/k8m/commit/f50276dac50ce97e848eccbf2690e537e2994601) 已增加通用搜索。后续会在界面上，逐个增加个性化的搜索选项
