### ISSUE TITLE
建议给节点这里加一些登录的按钮和

### ISSUE THREAD

**Issue by zhaomingcheng01** [weibaohui/k8m#8]
![image](https://github.com/user-attachments/assets/54df89bd-4039-45cf-ba84-d789b5fe4e0b)
![image](https://github.com/user-attachments/assets/1a520622-1f6e-41da-8ad4-f811db7215de)
这三个按钮的名字我是真的不敢操作,不知道是干嘛的

**Comment by weibaohui** [comment]
我参考研究下截图的功能处理思路
