### ISSUE TITLE
通用的界面能加个搜索框么,我不能一直翻页找啊

### ISSUE THREAD

**Issue by zhaomingcheng01** [weibaohui/k8m#9]
![image](https://github.com/user-attachments/assets/74b118b1-3b9c-404e-b0fe-de853edc063f)

日志和文件下载那里做的真棒

**Comment by weibaohui** [comment]
很好的建议，搜索功能必须安排上!

**Comment by weibaohui** [comment]
[https://github.com/weibaohui/k8m/commit/f50276dac50ce97e848eccbf2690e537e2994601](https://github.com/weibaohui/k8m/commit/f50276dac50ce97e848eccbf2690e537e2994601) 已增加通用搜索。后续会在界面上，逐个增加个性化的搜索选项
